steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/verisol/test:tag1', '.' ]
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/verisol/test:tag1'

artifacts:
  objects:
    location: 'gs://playwright-repdddorts/test/'
    paths: ['testreport.html']