steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/verisol/test:tag1', '.' ]
  secretEnv: ['MYSECRET']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/user_pass
    env: 'MYSECRET'

images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/verisol/test:tag1'


